name: instagram_video_story_share
description: A flutter plugin for iOS which shares a video file as an Instagram Story
version: 0.0.3
homepage: https://github.com/aytunch/instagram_video_story_share.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: InstagramVideoStorySharePlugin
